title: QuMESHS
description: Quantum Mesoscopic Electronic Semiconductor Heterostructure Solver
authors:
    - <a href="https://github.com/EdmundOwen">Dr Edmund Owen</a>
    - Prof. Crispin Barnes
project_url: https://github.com/EdmundOwen/QuMESHS
menubar_items:
    - features
    - download
    - documentation
    - examples

defaults:
    -
        scope:
            path: ''
        values:
            layout: default
